declare "${_COLORS_PREFIX_}ColorReset"="\e[m"

declare "${_COLORS_PREFIX_}Normal_Bold"="\e[1m"
declare "${_COLORS_PREFIX_}Normal_Underline"="\e[4m"
declare "${_COLORS_PREFIX_}Normal_Blinking"="\e[5m"
declare "${_COLORS_PREFIX_}Normal_Reverse"="\e[7m"

declare "${_COLORS_PREFIX_}Normal_Bold_Underline"="\e[1;4m"

declare "${_COLORS_PREFIX_}Red"="\e[31m"
declare "${_COLORS_PREFIX_}Green"="\e[32m"
declare "${_COLORS_PREFIX_}Yellow"="\e[33m"
declare "${_COLORS_PREFIX_}Blue"="\e[34m"
declare "${_COLORS_PREFIX_}Magenta"="\e[35m"
declare "${_COLORS_PREFIX_}Cyan"="\e[36m"
declare "${_COLORS_PREFIX_}White"="\e[37m"

declare "${_COLORS_PREFIX_}BoldRed"="\e[1;31m"
declare "${_COLORS_PREFIX_}BoldGreen"="\e[1;32m"
declare "${_COLORS_PREFIX_}BoldYellow"="\e[1;33m"
declare "${_COLORS_PREFIX_}BoldBlue"="\e[1;34m"
declare "${_COLORS_PREFIX_}BoldMagenta"="\e[1;35m"
declare "${_COLORS_PREFIX_}BoldCyan"="\e[1;36m"
declare "${_COLORS_PREFIX_}BoldWhite"="\e[1;37m"

declare "${_COLORS_PREFIX_}UnderlineRed"="\e[4;31m"
declare "${_COLORS_PREFIX_}UnderlineGreen"="\e[4;32m"
declare "${_COLORS_PREFIX_}UnderlineYellow"="\e[4;33m"
declare "${_COLORS_PREFIX_}UnderlineBlue"="\e[4;34m"
declare "${_COLORS_PREFIX_}UnderlineMagenta"="\e[4;35m"
declare "${_COLORS_PREFIX_}UnderlineCyan"="\e[4;36m"
declare "${_COLORS_PREFIX_}UnderlineWhite"="\e[4;37m"

declare "${_COLORS_PREFIX_}OnRed"="\e[41m"
declare "${_COLORS_PREFIX_}OnGreen"="\e[42m"
declare "${_COLORS_PREFIX_}OnYellow"="\e[43m"
declare "${_COLORS_PREFIX_}OnBlue"="\e[44m"
declare "${_COLORS_PREFIX_}OnMagenta"="\e[45m"
declare "${_COLORS_PREFIX_}OnCyan"="\e[46m"
declare "${_COLORS_PREFIX_}OnWhite"="\e[47m"
declare "${_COLORS_PREFIX_}OnBoldRed"="\e[1;41m"
declare "${_COLORS_PREFIX_}OnBoldGreen"="\e[1;42m"
declare "${_COLORS_PREFIX_}OnBoldYellow"="\e[1;43m"
declare "${_COLORS_PREFIX_}OnBoldBlue"="\e[1;44m"
declare "${_COLORS_PREFIX_}OnBoldMagenta"="\e[1;45m"
declare "${_COLORS_PREFIX_}OnBoldCyan"="\e[1;46m"
declare "${_COLORS_PREFIX_}OnBoldWhite"="\e[1;47m"
