declare "${_COLORS_PREFIX_LC_}color_reset"="\e[m"

declare "${_COLORS_PREFIX_LC_}normal_bold"="\e[1m"
declare "${_COLORS_PREFIX_LC_}normal_underline"="\e[4m"
declare "${_COLORS_PREFIX_LC_}normal_blinking"="\e[5m"
declare "${_COLORS_PREFIX_LC_}normal_reverse"="\e[7m"

declare "${_COLORS_PREFIX_LC_}normal_bold_underline"="\e[1;4m"

declare "${_COLORS_PREFIX_LC_}red"="\e[31m"
declare "${_COLORS_PREFIX_LC_}green"="\e[32m"
declare "${_COLORS_PREFIX_LC_}yellow"="\e[33m"
declare "${_COLORS_PREFIX_LC_}blue"="\e[34m"
declare "${_COLORS_PREFIX_LC_}magenta"="\e[35m"
declare "${_COLORS_PREFIX_LC_}cyan"="\e[36m"
declare "${_COLORS_PREFIX_LC_}white"="\e[37m"

declare "${_COLORS_PREFIX_LC_}bold_red"="\e[1;31m"
declare "${_COLORS_PREFIX_LC_}bold_green"="\e[1;32m"
declare "${_COLORS_PREFIX_LC_}bold_yellow"="\e[1;33m"
declare "${_COLORS_PREFIX_LC_}bold_blue"="\e[1;34m"
declare "${_COLORS_PREFIX_LC_}bold_magenta"="\e[1;35m"
declare "${_COLORS_PREFIX_LC_}bold_cyan"="\e[1;36m"
declare "${_COLORS_PREFIX_LC_}bold_white"="\e[1;37m"

declare "${_COLORS_PREFIX_LC_}underline_red"="\e[4;31m"
declare "${_COLORS_PREFIX_LC_}underline_green"="\e[4;32m"
declare "${_COLORS_PREFIX_LC_}underline_yellow"="\e[4;33m"
declare "${_COLORS_PREFIX_LC_}underline_blue"="\e[4;34m"
declare "${_COLORS_PREFIX_LC_}underline_magenta"="\e[4;35m"
declare "${_COLORS_PREFIX_LC_}underline_cyan"="\e[4;36m"
declare "${_COLORS_PREFIX_LC_}underline_white"="\e[4;37m"

declare "${_COLORS_PREFIX_LC_}on_red"="\e[41m"
declare "${_COLORS_PREFIX_LC_}on_green"="\e[42m"
declare "${_COLORS_PREFIX_LC_}on_yellow"="\e[43m"
declare "${_COLORS_PREFIX_LC_}on_blue"="\e[44m"
declare "${_COLORS_PREFIX_LC_}on_magenta"="\e[45m"
declare "${_COLORS_PREFIX_LC_}on_cyan"="\e[46m"
declare "${_COLORS_PREFIX_LC_}on_white"="\e[47m"
declare "${_COLORS_PREFIX_LC_}on_bold_red"="\e[1;41m"
declare "${_COLORS_PREFIX_LC_}on_bold_green"="\e[1;42m"
declare "${_COLORS_PREFIX_LC_}on_bold_yellow"="\e[1;43m"
declare "${_COLORS_PREFIX_LC_}on_bold_blue"="\e[1;44m"
declare "${_COLORS_PREFIX_LC_}on_bold_magenta"="\e[1;45m"
declare "${_COLORS_PREFIX_LC_}on_bold_cyan"="\e[1;46m"
declare "${_COLORS_PREFIX_LC_}on_bold_white"="\e[1;47m"
